### ISSUE TITLE
Guild Member GEXP Inconsistency 

### ISSUE THREAD

**Issue by SimplyNo** [HypixelDev/PublicAPI#204] opened 2020-03-18 22:24 UTC
When requesting to `api.hypixel.net/guild?key=KEY&name=GUILD_NAME,` the stats for gexp earned for a member is sometimes bugged, not showing a date, or having the dates out of order. 

How it should be is this: `
                "expHistory": {
                    "2020-03-19": 23529,
                    "2020-03-18": 64398,
                    "2020-03-17": 60033,
                    "2020-03-16": 138558,
                    "2020-03-15": 73443,
                    "2020-03-14": 69392,
                    "2020-03-13": 19758
                }
`Which is how it is most of the time but sometimes it outputs it like this:
`                "expHistory": {
                    "2020-03-19": 4815,
                    "2020-03-18": 2851,
                    "2020-03-17": 5379,
                    "2020-03-16": 11274,
                    "2020-03-14": 6221,
                    "2020-03-13": 1064
                }
` Missing a day

See this forum post: https://hypixel.net/threads/api-help-inconsistencies-with-guild-member-gexp.2676505/#post-18646625

**Comment by Kuba314** [comment] 2020-03-22 11:35
duplicate of #145

**Comment by Kuba314** [comment] 2020-03-22 11:36
Duplicate of #145

**Comment by SimplyNo** [comment] 2020-03-22 15:08
> Duplicate of #145

that is weird I thought i checked.. Eh anyways do you mind if I ask you if you ever found a way to solve this issue?

**Comment by Kuba314** [comment] 2020-03-22 15:44
@SimplyNo You can't fix this. The issue is in their API that for some reason doesn't send the whole 7 days, sometimes... You can of course check, whether the length is < 7 and then maybe send the request again or handle it in your own way.

**Comment by Plancke** [comment] 2020-09-13 19:21
Closed, see https://github.com/HypixelDev/PublicAPI/issues/145#issuecomment-688327264

**Closed by Plancke** 2020-09-13 19:21 UTC
