### ISSUE TITLE
Impossible to get Player JsonObject?

### ISSUE THREAD

**Issue by hjongh** [HypixelDev/PublicAPI#46] opened 2017-01-11 05:41 UTC
So in order to get player JsonObject, you need to get it from 'result' from PlayerReply after you make a Player Request to the API. But the lambda, doesnt work because PlayerReply is not a functional interface. And the API's async method requires class that extends AbstractReply to work, and because AbstractReply is an abstract class, we cannot extend functional interface from it. So essentially from what I'm seeing, the way async and the api has been restructured by Plancke makes it impossible to get JsonObject and parse for player data... Or am I missing something?

**Comment by Plancke** [comment] 2017-01-11 12:05
I just cloned the most recent version of master and the player example is working fine, I'm able to use methods defined in PlayerReply

![image](https://cloud.githubusercontent.com/assets/1756802/21847839/4e852c5a-d7fe-11e6-85dc-aa2b7b4b805c.png)

Can you show me what your IDE is complaining about and where?

**Comment by hjongh** [comment] 2017-01-11 16:37
Hey Plancke, thanks for replying. Here's the error I'm getting in my Eclipse:

![lambda issue](https://cloud.githubusercontent.com/assets/16041102/21856436/dd944746-d7d6-11e6-8ece-bf429efa9e97.PNG)

Perhaps the fact that I'm using an older version of your API is causing this? I'm using the same jar file I downloaded somewhere like 6 months ago. But I don't think that's the case because the getAsync methods and everything are the same structure as in your examples, just this one 'functional interface' error I'm getting...  (Also I was confused with this last time, so I just downloaded your api from a random website I think. Is the correct way to get a Hypixel API jar by cloning your project and then making it into a jar from eclipse?)

**Comment by hjongh** [comment] 2017-01-12 00:11
Hey Plancke, 

I think you are missing Joda-Time library from the list of dependencies in the API readme description, I think you forgot to add it when you updated the api.

**Comment by hjongh** [comment] 2017-01-12 05:44
Hey Plancke,

I got the lambda to work, but I had question about your sync vs async method. Last time I used your api I tried to use async method but it crashed my minecraft, so I just used sync method. Looking closer this time same thing is happening, and it seems to be because of the System.exit(0) at the async method. I debugged with messages around it, and right when Minecraft reaches the system.exit(0), Minecraft (java) just stops and the game freezes. I think it may be Forge specific. Do you know how I can fix this?

**Comment by Semx11** [comment] 2017-01-12 10:02
1: https://github.com/HypixelDev/PublicAPI/blob/master/Java/pom.xml#L27-L31

2: I can't seem to find the `System.exit(0)` statement you described. You might have to clone the repo again because `System.exit()` obviously 'crashes' Minecraft (or any other Java program, really).
https://github.com/HypixelDev/PublicAPI/blob/master/Java/src/main/java/net/hypixel/api/HypixelAPI.java#L138-L147

3: That is an authentication error which happens in the Forge development environment.

**Comment by hjongh** [comment] 2017-01-12 15:09
Hey Semx11, System.exit(0) can be found as part of Plancke's GetPlayerReply example, he used it to exit callback on the asynchronous request, and I'm not sure if there's a way to exit the asynchronous request without using system.exit and Minecraft shutting down. I tried using security manager to confine the system.exit but forge does not allow me to change the system security manager.

**Comment by Semx11** [comment] 2017-01-12 16:48
The example just shows basic usage of the API. It is not applicable in all situations. [GetPlayerExample.java](https://github.com/HypixelDev/PublicAPI/blob/master/Example/src/main/java/net/hypixel/example/GetPlayerExample.java) only has a main method, nothing else.

This is why it has to wait for the async request to complete, otherwise the program would exit before it has finished. It is using the `.await()` method from [ExampleUtil.java](https://github.com/HypixelDev/PublicAPI/blob/master/Example/src/main/java/net/hypixel/example/ExampleUtil.java):
```java
static void await() {
    while (!Thread.interrupted()) {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```
This method simply waits (hence the name) until the thread is interrupted, and checks the status each second (1000ms). Obviously, the Callback would 'exit' (finish executing) on it's own, but otherwise the example would keep waiting for the thread to be interrupted. Since it's an example, and this is the only functionality, it simply exits the program using `System.exit(0)`. Exit code `0` means that termination went fine, and that it was expected behavior.

Minecraft however will always run until it crashes or is closed/terminated. This means that you don't need to `.await()` to prevent the program from closing, because Minecraft is the main process and is still running (`System.exit()` will terminate Minecraft).

This is why you use the Callback interface, where you can 'specify' code to run when the async request is complete.

**Comment by hjongh** [comment] 2017-01-12 18:54
Thanks so much for explaining. So to my understanding System.exit(0) isn't necessary to exit callback, and is just to end the example. Await is just keeping the program running until System.exit(0) occurs? 

So then I can just remove System.exit(0) as well as Await, because callback will exit on its own and Minecraft will keep the 'code running'?

Is this the correct usage then?: 
![hisemx11](https://cloud.githubusercontent.com/assets/16041102/21903054/2b340054-d8b3-11e6-8465-755308766548.PNG)

Also there's a little freeze (1 second) in game when the command is being executed, it was there when I was using sync method but I thought using async method would fix this? Because it runs in the background while other processes can execute?

**Comment by AgentK20** [comment] 2017-01-12 19:52
> So then I can just remove System.exit(0) as well as Await, because callback will exit on its own and Minecraft will keep the 'code running'?
Correct. Specifically, the API implementation spins up some threads that will keep the program running even after the request is completed. System.exit(0); kills the program, and actually isn't really necessary in this context.

Ideally, what you want to do is not call the await method at all. The callback you provide is the code that will be fired when the response is received from the API, and by not _await_'ing the rest of Minecraft is able to continue working on things. This is why your Minecraft client freezes when you do the await call.

On the other hand, if you use truly async code with the callback, you have to make sure that the operations that you're calling are thread-safe, since the callback is executed outside of the main Minecraft thread.

**Comment by hjongh** [comment] 2017-01-13 06:52
Hey folks, just wanted to say thanks so much for chiming in to help! I got the little stats mod that I wanted to create using this API to work. Appreciate you guys spending your time to help me, thanks so much for that.

**Closed** 2017-01-15 12:25 UTC
