### ISSUE TITLE
[Skyblock] Add selected / active profile

### ISSUE THREAD

**Issue by edwinli123456** [HypixelDev/PublicAPI#235] opened 2020-05-07 22:55 UTC
Add a field under the player endpoint, which shows which profile in skyblock is active.

**Comment by puppy0cam** [comment] 2020-05-07 23:16
Duplicate of #138

**Comment by Minikloon** [comment] 2020-05-13 22:54
It's available in stats.SkyBlock.account.selected_profile

**Closed by Minikloon** 2020-05-13 22:54 UTC

**Comment by Picsou993** [comment] 2020-05-13 23:00
It seems that we do not have this field on the Public API, here is an exemple with my SkyBlock Stats with the `player` method:
![API  SkyBlock Active Profile](https://user-images.githubusercontent.com/33390780/81874474-3bce1180-957e-11ea-9bd2-711b9366720a.PNG)
