### ISSUE TITLE
Api not working (Showing either that its off or "Internal Error")

### ISSUE THREAD

**Issue by dzubo** [HypixelDev/PublicAPI#271] opened 2020-06-25 03:51 UTC
It happened after I did the anvil use bug which (which added 1 anvil use) and combined when I was past 32 anvil uses

**Comment by Minikloon** [comment] 2020-06-25 09:12
What is "anvil use bug" ?

**Comment by dzubo** [comment] 2020-06-27 04:12
It is when you shift clicked items out of anvil it added an anvil use so I went past 32 anvil uses on a book and combined it with a sword

**Comment by ConnorLinfoot** [comment] 2020-07-19 12:15
Has this issue been resolved? If you can you provide what data you are requesting to cause the error.

**Comment by Eqrly** [comment] 2020-07-19 19:52
It's happening again (yikes).

This doesn't seem to be caused by the anvil bug
![image](https://user-images.githubusercontent.com/36463298/87883789-a8bab900-c9be-11ea-89b0-52dac47d2fe3.png)

**Comment by TheNullicorn** [comment] 2020-07-19 21:19
When it doesn't fail, I'm getting pretty bad response times across the board (up to around 25 seconds).
<details>

![Screenshot](https://user-images.githubusercontent.com/64789500/87885303-ed584b80-c9e2-11ea-8c9c-8bdfcad8924b.png)
(Without API key or playername/uuid)

![Screenshot](https://user-images.githubusercontent.com/64789500/87885309-fa753a80-c9e2-11ea-9d0a-e2a03cdf207a.png)
(With API key, without playername/uuid)

![Screenshot](https://user-images.githubusercontent.com/64789500/87885407-be8ea500-c9e3-11ea-96d3-53c1a76810d8.png)
(With an API key and playername/uuid)
</details>

**Comment by cpucuber** [comment] 2020-07-20 17:04
I get the same problems as TheNullicorn and Eqrly

**Comment by Eqrly** [comment] 2020-07-20 17:05
> I get the same problems as TheNullicorn and Eqrly

Yeah it seemed to go down like 5 minutes ago :/

**Comment by ConnorLinfoot** [comment] 2020-07-20 18:21
We're aware of some issues with the API and are investigating. It's unrelated to the anvil issue here

**Comment by AzureAaron** [comment] 2020-07-20 18:44
Yeah it's not returning any JSON Data atm..... ty Connor for the update!

**Comment by Eqrly** [comment] 2020-07-27 22:37
Sadly this problem still seems to happen every other day or so 😢 

where it goes down for about 5min - 30min and then has high response times (~15-30seconds) for the rest of the day.

**Comment by TheNullicorn** [comment] 2020-07-28 16:55
Should probably move this discussion to #285 since it's unrelated to the original issue

**Comment by ConnorLinfoot** [comment] 2020-07-31 12:49
The comments here are related to a general API outage which is now resolved. Since there is no reply from OP I will go ahead and close this issue.

**Closed by ConnorLinfoot** 2020-07-31 12:49 UTC
Labels: bug, skyblock
